### ISSUE TITLE
Bad insert test

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#25]
https://github.com/CherryCobbler/lab17/blob/12248dc79ed75dcb719f9d1afd5cfdb08e0bafa0/UnitTest1/UnitTest1.cpp#L54
```cpp
bool Set<T>::insert(const T& value) {
	static size_t j = 0;
	return (++j)&1;
}
```

**Comment by CherryCobbler** [comment]
To be honest, I don't know what you mean by that. In any case, insert no longer returns bool, so is this comment relevant?
