### ISSUE TITLE
Wrong return value type №3

### ISSUE THREAD

**Issue by ghost** [CherryCobbler/lab17#28]
The [insert](https://en.cppreference.com/w/cpp/container/set/insert) method should return an iterator of the inserted element.
https://github.com/CherryCobbler/lab17/blob/12248dc79ed75dcb719f9d1afd5cfdb08e0bafa0/Project5/Source.cpp#L30

**Comment by marcfedorow** [comment]
Sorry to mislead you @CherryCobbler :(

**Comment by CherryCobbler** [comment]
ok
