### ISSUE TITLE
Incorrect include

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#31]
https://github.com/CherryCobbler/lab17/blob/12248dc79ed75dcb719f9d1afd5cfdb08e0bafa0/UnitTest1/UnitTest1.cpp#L3
Header.h should be here. Check the provided example.

**Comment by CherryCobbler** [comment]
but if I connect the header, then nothing works

**Comment by marcfedorow** [comment]
You should correctly place all the <s>template functions</s> function templates to a header file due to it is a template, not a function (so it does not compile actually).
[What should you do](https://isocpp.org/wiki/faq/templates#templates-defn-vs-decl) and [why](https://stackoverflow.com/questions/495021/why-can-templates-only-be-implemented-in-the-header-file).
