### ISSUE TITLE
Invalid array copy

### ISSUE THREAD

**Issue by ghost** [CherryCobbler/lab17#32]
`busy` (collection size) can be greater than `size` (collection capacity) in the case of `size` variable overflow.
It should look like this:
```cpp
array = new T[capacity]; 
for (size_t i = 0; i < capacity; ++i)
.....
```
https://github.com/CherryCobbler/lab17/blob/12248dc79ed75dcb719f9d1afd5cfdb08e0bafa0/Project5/Source.cpp#L67-L71

**Comment by CherryCobbler** [comment]
busy cannot become larger than size because each time one element is added, and the space for size is re-allocated to size * 2 (or size + 10 until recent changes)

**Comment by ghost** [comment]
> busy cannot become larger than size because each time one element is added, and the space for size is re-allocated to size * 2 (or size + 10 until recent changes)

If you retry to read my sentence you find what I mean only the case of overflow.

**Comment by marcfedorow** [comment]
If you do not want to change this logic you should add an overflow check (if `size` is overflown, throw some exception; e.g. `std::overflow_error`). You can easily check an overflow by comparing new size and the previous one.
