### ISSUE TITLE
Instructions ignoration

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#41]
https://github.com/CherryCobbler/lab17/blob/379196047a093c72a3de8a8422289de5f53b1ec7/Project5/Source.cpp#L1
Why do you ignore direct instructions? #31 
You should include your file which declares function templates to a header.
Your Source.cpp **IS NOT A COMPILATION UNIT** actually.

**Comment by CherryCobbler** [comment]
Because I solve problems consistently and I haven't gotten to this one yet

**Comment by marcfedorow** [comment]
You can solve problems consistently in develop branch but not in master one.
If you pushed something to master it triggers a full-check.
