### ISSUE TITLE
False description

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#45]
https://github.com/CherryCobbler/lab17/blob/379196047a093c72a3de8a8422289de5f53b1ec7/Project5/Source.cpp#L19
It is _not_ created yet! New can throw an std::bad_alloc exception by itself!

**Comment by CherryCobbler** [comment]
So I don't need to do a "try-catch"there?

**Comment by marcfedorow** [comment]
This issue just reports that information that you give is incorrect.
If you do really want to handle it properly you could be forced to insert another try in your catch block.
