### ISSUE TITLE
Obscure logic

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#55]
https://github.com/CherryCobbler/lab17/blob/379196047a093c72a3de8a8422289de5f53b1ec7/Project5/Source.cpp#L115
This method is long and hard to read.
You should just find an element and de-inserte it (just use std::copy or std::copy_backward).
It could be good to decrease capacity of your container (e.g. if size <= capacity/4 than capacity /= 2).

**Comment by CherryCobbler** [comment]
Since some functions return iterators, in order to protect private data from the user, I made return const T*. But copy doesn't work with constant data, so I still have to do loops. Or is there another way out of this situation?

**Comment by marcfedorow** [comment]
While it is a class function it has a direct access to its memory.
You can calculate index using std::distance.

**Comment by marcfedorow** [comment]
Also your functions return pointers, not iterators

**Comment by CherryCobbler** [comment]
distance doesn't work with const either. or what did you mean? I see 3 solutions: I will write my distance that works with const (a bad idea); I will write everything in cycles (I can modify the original version using copy with array+i, and so on); I will stop returning a constant value in find_it and the problem will disappear, but then I do not know how to protect private data from the user.
