### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#56]
https://github.com/CherryCobbler/lab17/blob/379196047a093c72a3de8a8422289de5f53b1ec7/UnitTest1/UnitTest1.cpp#L11-L29
Well this version is better than previous for sure.
Still not good.

**Comment by CherryCobbler** [comment]
I wrote that the tests are not ready yet

**Comment by marcfedorow** [comment]
You should NOT close any issue if it has not been done!
