### ISSUE TITLE
Destructor

### ISSUE THREAD

**Issue by ghost** [CherryCobbler/lab17#57]
It would be better if you assign the pointer to `nullptr`
https://github.com/CherryCobbler/lab17/blob/379196047a093c72a3de8a8422289de5f53b1ec7/Project5/Source.cpp#L25-L28

**Comment by CherryCobbler** [comment]
What for? I'm just deleting an array, right?

**Comment by marcfedorow** [comment]
Because in the case of manual calling of destructor you’ll get an UB trying to delete deallocated memory
