### ISSUE TITLE
Usability of your source

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#65]
https://github.com/CherryCobbler/lab17/blob/7e4ce367116424e6013f6ee51fcbaa8029d78ebd/Project5/Source.cpp#L105
Are you sure it is OK to post code like this to master branch?

**Comment by CherryCobbler** [comment]
Well, Nikita said fill it in, I'm like, Okay

**Comment by CherryCobbler** [comment]
I admit, I completely forgot about erase when I decided to fill it in
