### ISSUE TITLE
New old issues

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#69]
There are lots of unsolved stuff
- #33 You still push directly to master #68
- https://github.com/CherryCobbler/lab17/issues/56#issuecomment-665004146 You still closing unfixed issues (#46 #53 -> #62; #1 -> #66)
- #64 You changed this line in the last commit so solving problems consistently does not explain #7 still not fixed (#47 gives you a correct code you did not use for some reason).
- #63 #67 still not solved. It was not hard to do, probably less than 5 minutes (including commit and merge).
- #60 still not done while the last commit changes the unit-test file. "I do functions first" seems to be pointless since you should check somehow if they work. You have no tests so if you break something there is no way to find that any more.
It should not work like you just upload some random code and we check it. You should check it first. How do you check it using zero tests and `int main(){return 0;}` is inapprehensible.

**Comment by CherryCobbler** [comment]
how do #64 and #47  relate to #7  if they are different functions?
