### ISSUE TITLE
Senseless throw

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#7]
https://github.com/CherryCobbler/lab17/blob/12248dc79ed75dcb719f9d1afd5cfdb08e0bafa0/Project5/Source.cpp#L11-L22
It makes no sense to throw an exception just to handle it inside the same function.
`if (nsize < 0) nsize = 1;` fits much better.

**Comment by CherryCobbler** [comment]
I am on assignment to push an exception there

**Comment by marcfedorow** [comment]
But you do not do it actually.
You should NOT catch it immediately to make any sense.
