### ISSUE TITLE
?

### ISSUE THREAD

**Issue by marcfedorow** [CherryCobbler/lab17#71]
https://github.com/CherryCobbler/lab17/blob/72605f13c1f0f35d73253b60255eb1117e4d86aa/Project5/Header.h#L1-L5

**Comment by CherryCobbler** [comment]
I forgot to remove pragma once.

**Comment by marcfedorow** [comment]
So remove it and commit with “close #71” comment.
There is no need in commenting.

Cherry <notifications@github.com> schrieb am So. 2. Aug. 2020 um 13:01:
